server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  redis:
    host: 192.168.231.134
    port: 6379
#    password: 123321
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug

# 接口文档配置 http://localhost:8080/api/doc.html
knife4j:
  enable: true  # 启用 Knife4j
  openapi:
    title: "接口文档"  # 设置文档标题
    version: "1.0"  # 设置文档版本
    group:
      default:  # 默认组配置
        api-rule: package  # 按照包扫描规则生成文档
        api-rule-resources:
          - com.hmdp.controller  # 要扫描的包路径，通常是你的控制器所在的包


